[Feat] Base 파일들 추가
GEON-PPANG/GEON-PPANG-iOS pull request #14
Opened 2023-07-04 06:56 UTC by seongmin221

## 🌁 Background

조금 더 편한 개발을 위해 Base 관련 요소들을 추가했습니다 !

## 📱 Screenshot

- 

## 👩‍💻 Contents

- BaseViewController 추가
- BaseTableViewCell 추가
- BaseCollectionViewCell 추가

## ✅ Testing

직접 사용해보시죠 !

## 📝 Review Note

- 원래 setNavigationBar 도 넣는데, 아직 커스텀이 만들어지지 않기도 했고, 좋은 방법일까 라는 생각이 들어서 빼두었습니다 ~

## 📣 Related Issue

- close #13

## 📬 Reference

2023-07-04 10:55 UTC, jeongdung-eo approved these changes
믓찌다 :)

2023-07-05 07:03 UTC, ckkim817 requested changes
P1 확인 부탁

2023-07-05 07:22 UTC, hansolnoh95 commented
BaseViewController에 gesture(swipe, keyboard, ...) 관련 recognizer나 뷰에 기본 backgroundColor 정도도 함께 들어가면 좋을 것 같네요!

2023-07-05 08:30 UTC, seongmin221 commented on GEON-PPANG-iOS/Presentation/Common/Base/BaseViewController.swift
> +        setLayout()
지금 깃허브가 이상해서 커밋 코드를 쓸 수가 없네요 .. 캐치해주셔서 감사합니다 ~

2023-07-05 08:31 UTC, seongmin221 commented on GEON-PPANG-iOS/Presentation/Common/Base/BaseViewController.swift
> +    func setStyle() {
엇 ! 제가 잊고 있었군요 우하하ㅏ... setStyle 을 항상 써온터라... 헷갈렸습니다 ㅎ하... 고쳤습니다 !

2023-07-06 02:46 UTC, ckkim817 approved these changes
어푸룹~ 고생하셨습니다

2023-07-06 03:28 UTC, merged